# Generated by Django 5.2.6 on 2025-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, help_text='Número para contato, idealmente com WhatsApp.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Notas importantes, como alergias ou preferências.', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
